### ISSUE TITLE
Style guide/ESLint or alike

### ISSUE THREAD

**Issue by ItsAzaria** [the-programmers-hangout/Chronos#12]
Some kind of enforced style for the entire codebase

**Comment by ridays2001** [comment]
Can I work on this?
I have written an entire eslint config of my own [(eslint-config-tulip)](https://github.com/ridays2001/eslint-config-tulip).
I can adjust some configs to match the ones that we currently use (double quotes, 2 spaces indentation, and trailing commas)

[ PS - It would be better if someone gives me the green signal before I start working ]

**Comment by ItsAzaria** [comment]
Feel free, most the code now either isn't formatted or just has a basic prettier on it - might be for another issue but we should investigate auto formatting via CI

**Comment by ridays2001** [comment]
Okie. So, can I change the current one? Or should I make the config stick to the current one as much as possible?
