### ISSUE TITLE
Fix: config file

### ISSUE THREAD

**Issue by ridays2001** [the-programmers-hangout/Chronos#28]
- Some of the IDs are parsed and stored as numbers, while the others are stored as strings. The API directly provides strings, so it's better to convert all of them to strings.
- The `BotOwner` is in the title case. But, we are using `camelCase` rename all instances of it.
- The indentation of the `config.json` file is messed up. Needs fixing.

**Comment by Calcium3d** [comment]
ill take this up
shouldnt be too hard

**Comment by Calcium3d** [comment]
famous last words

**Comment by ridays2001** [comment]
Closed via #31 and #38
