### ISSUE TITLE
Fix: bot owner

### ISSUE THREAD

**Issue by ridays2001** [the-programmers-hangout/Chronos#29]
-  We've made bot owner configurable. But, we haven't actually implemented it.
- The task is to replace all instances of `process.env.OWNERID` with the `botOwner` that is in the config file.
- Make sure that you don't break the code.
- Use `botOwner` instead of the current `BotOwner` because we need to stick to `camelCase`.

**Comment by Andreybest** [comment]
Hey! I can try doing this. Can you assign this task to me?

**Comment by ridays2001** [comment]
@Andreybest What's your username on discord?

**Comment by Andreybest** [comment]
@ridays2001 Vasyugan#3458

**Comment by ridays2001** [comment]
@Andreybest I cannot find you in TPH Discord. If you're there, then please ping me in #chronos-bot channel under "Community" section. This repo is limited to our community members only as of now. But, let's see what others have to say.

**Comment by Andreybest** [comment]
Im not the member of your server, but if you want I can work on this issue.

**Comment by ridays2001** [comment]
Um, idk. I can't assign this to you. I'm not sure whether we're allowing non tph members yet. There are a lot of members ready to work on this. We're just discussing it on discord and waiting for someone with less experience to take it.

**Comment by ridays2001** [comment]
@Andreybest You can join our server - [Here](https://discord.gg/programming). Use the #chronos-bot channel for discussion. Ping me there and I'll assign you to the issue.
