### ISSUE TITLE
Fix: inhibitor bug

### ISSUE THREAD

**Issue by ridays2001** [the-programmers-hangout/Chronos#34]
- The inhibitor disables access by default. (Because there will be at least one entry in the config file).
- Set the default to guild admin `message.member.permissions.has('ADMINISTRATOR')` or bot owner `this.client.isOwner(message.author)` if there are no stored configs for the guild.
- If you return `true` it'll block the command from being run (`inhibit` it).
- While you're at it, try to clean up the code, if possible.

**Comment by codevenkat** [comment]
Just asking about the inhibitor file,
`const guildConfiguration = config.guildConfigurations.find(el => el.guildID === parseInt(message.guild.id, 10));`

Why is there a `parseInt()` in that line? AFAICS `guildConfigurations` are added with strings and not ints

**Comment by ridays2001** [comment]
@codevenkat It's because the config file was a mess initially. Some values were used as numbers and some were used as strings. There is even an issue to fix it #28
