### ISSUE TITLE
Refactor: getGuildConfig()

### ISSUE THREAD

**Issue by ridays2001** [the-programmers-hangout/Chronos#37]
- Currently, when we want to get the saved guildConfig for a guild, we use different ways and it's inefficient.
- Your task is to build a clean function that accepts Guild or guild ID as input and return `undefined` or the guild config object depending on whether it's present or not.
- Put the file in `src/utilities/` folder.
- While you're at it, replace all instances of guildConfigurations with your newly created function.

**Comment by sidtr0** [comment]
I’m up for doing this if anyone else doesn’t want to do it. Remember that I still have another command to write, so you can still grab it.

**Comment by codevenkat** [comment]
@DracTheDino Could I take a go at this one in case you haven't started working on it yet?

**Comment by ridays2001** [comment]
Assigned to @codevenkat 👍🏻

**Comment by DracTheDino** [comment]
@codevenkat 100% go ahead, I’ll assign you to the issue.
