### ISSUE TITLE
Commands should be limited to a configurable role

### ISSUE THREAD

**Issue by ItsAzaria** [the-programmers-hangout/Chronos#4]

**Comment by ddivad195** [comment]
This can be possible using Akairo inhibitors:
https://discord-akairo.github.io/#/docs/main/master/inhibitors/inhibtypes

To complete this task, an inhibitor that limits command access to only people with the "staff" role (set via the configuration from #7 ) should be created.

**Comment by Calcium3d** [comment]
well I've already set a staff role in the config, just grab that
