### ISSUE TITLE
A mention embed

### ISSUE THREAD

**Issue by ItsAzaria** [the-programmers-hangout/Chronos#6]
![image](https://user-images.githubusercontent.com/34754130/93808761-573fdc00-fc44-11ea-82d1-0bdaab518cab.png)
so a lot of bots have this mention -> info embed. Would be very useful for gathering all that information in one place (removes the need for a ping and uptime command)

**Comment by sidtr0** [comment]
Okay, great, I'll be able to work on this.

**Comment by sidtr0** [comment]
In the above example you gave, are the contributors hard-coded into the embed?

**Comment by sidtr0** [comment]
Pull Request #11 fixing the issue.

**Comment by ItsAzaria** [comment]
Hard coded is fine, if they're used elsewhere in the future a locale file or alike should be implemented

**Comment by ItsAzaria** [comment]
Closed by #17
