### ISSUE TITLE
Config system

### ISSUE THREAD

**Issue by ItsAzaria** [the-programmers-hangout/Chronos#7]
A lot of commands will be saving config to a flat json file. We need some kind of config system to make that all possible.

things that will be saved in there are: current slowmode per channel, current prefix. 
Attention should be taken here to assure that if needed the config can be multi guild. I suggest a json file with this format to start with, extra fields may be needed in the future

```{
  "botOwner": 345541952500006912,
  "guildConfigurations": [
    {
      "guildID": 699595207720566824,
      "logChannel": 735931902359502888,
      "prefix": "+",
      "staffRole": "staff_role_name",
      "slowmodeChannels": [
        "735931902359502888": 1800,
        "757602062241497189": 2400
      ]
    }
  ]
}

**Comment by Calcium3d** [comment]
i can take this up, but will i copy the already given one or make another new one

**Comment by Calcium3d** [comment]
also ill add the id of every channel
so incase you need you can slowmode any channel you wish

**Comment by Calcium3d** [comment]
Also i need the log channel name

**Comment by ItsAzaria** [comment]
These are just example configs, they should be generated if they don't exist. Everything within guildconfigurations not including the guildID should eventually be configurable by commands

**Comment by Calcium3d** [comment]
okay

**Comment by Calcium3d** [comment]
ill add all the command configurations that i can

**Comment by Calcium3d** [comment]
ill do most of the config commands, then create the PR

**Comment by Calcium3d** [comment]
i think we can close this
